---
  deployment:
    tasks:
      - export DEPLOYPATH_WEB=/home/drtcl/web/
      - export DEPLOYPATH_PUBLIC=/home/drtcl/public/
      - /bin/rsync -av web/ $DEPLOYPATH_WEB
      - /bin/rsync -av public/ $DEPLOYPATH_PUBLIC