---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolutionweli/public_html/pruebagit.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolutionweli/web2/
      - /bin/rsync -av ./ $DEPLOYPATH
